Vagrant.configure("2") do |config|
  # Installing an ubuntu
  config.vm.box = "ubuntu/bionic64"
  # Adding a public network interface to that VM
  config.vm.network "public_network",type: "dhcp", bridge: "en0: Ethernet"

  # Doing the provisionning via a script shell
  config.vm.provision "shell" do |shell|
    shell.path = "jenkins.sh"
  end


end
